branches:
  only:
  - nextgen
image: Visual Studio 2015
environment:
  QTDIR: C:\Qt\5.10\msvc2015_64
  VK_VERSION: 1.1.73.0
  VK_INSTALLER: 'vulkdansdk_%VK_VERSION%.exe'
  VULKAN_SDK: 'C:\VulkanSDK\%VK_VERSION%'
  matrix:
    - CONFIG: Debug
    - CONFIG: Release
cache:
  - '%VK_INSTALLER%'
  - external-deps
init:
  - C:\"Program Files (x86)"\\\"Microsoft Visual Studio 14.0\"\VC\vcvarsall.bat amd64
  - set PATH=%VULKAN_SDK%\Bin;%QTDIR%\bin;%PATH%
  - ps: "[Environment]::SetEnvironmentVariable(\"CONFIG_LOWER\", $env:CONFIG.ToLower())"
  - cmake --version
  - msbuild /ver
  - nmake /P
  - qmake --version
install:
  - if not exist external-deps install.bat
  - ps: "If (!(Test-Path $env:VK_INSTALLER)) {([Net.ServicePointManager]::SecurityProtocol=\"tls12, tls11, tls\") -AND ($ProgressPreference = 'SilentlyContinue') -AND(Invoke-WebRequest \"https://sdk.lunarg.com/sdk/download/$env:VK_VERSION/windows/VulkanSDK-$env:VK_VERSION-Installer.exe?Human=true;u=\" -OutFile $env:VK_INSTALLER)}"
  - start %VK_INSTALLER% /S
  - mkdir build\gameplay\%CONFIG%
  - cd build\gameplay\%CONFIG%
  - qmake CONFIG+=%CONFIG_LOWER% -spec win32-msvc ..\..\..\gameplay\gameplay.pro
  - cd ..\..\..
  - mkdir build\gameplay-app\%CONFIG%
  - cd build\gameplay-app\%CONFIG%
  - qmake CONFIG+=%CONFIG_LOWER% -spec win32-msvc ..\..\..\gameplay-app\gameplay-app.pro
  - cd ..\..\..
  - mkdir build\gameplay-editor\%CONFIG%
  - cd build\gameplay-editor\%CONFIG%
  - qmake CONFIG+=%CONFIG_LOWER% -spec win32-msvc ..\..\..\gameplay-editor\gameplay-editor.pro
  - cd ..\..\..
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIG% -G "Visual Studio 14 2015 Win64" ..
build_script:
  - msbuild GamePlay.sln /property:Configuration=%CONFIG%
  - cd gameplay\%CONFIG%
  - nmake
  - cd ..\..\gameplay-app\%CONFIG%
  - nmake
  - cd ..\..\gameplay-editor\%CONFIG%
  - nmake
